project:
  type: website
  
  
website:
  title: "Coastal Ecogeomorphic Systems Lab"
  navbar:
    collapse-below: sm 
    left:
      - text: "Home"
        href: ces.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Research"
        href: research.qmd
      - text: "People"
        href: people.qmd
      - text: "Equipment"
        href: equipment.qmd
      - text: "Computational Geomorphology and Modeling Lab"
        href: cgmlab.qmd
  

  page-footer:
    right: "© pschmutz, University of West Florida"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    mainfont: Arial
