project:
  type: website
  
  
website:
  title: "Coastal Ecogeomorphic Systems Lab"
  site-url: "https://coastal-ecogeomorphic-systems-lab.github.io/CES-Lab/"
  navbar:
    collapse-below: sm 
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Research"
        href: research.qmd
      - text: "People"
        href: people.qmd
      - text: "Facilities"
        href: equipment.qmd
      - text: "Project Data"
        href: data.qmd     

  page-footer:
    right: "© pschmutz, University of West Florida"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    mainfont: Arial
