---
title: "Publications"
---

**Bolded author indicates the lab director.**  
<sup>U</sup> Undergraduate student co-author  
<sup>G</sup> Graduate student co-author


### Peer-Reviewed Manuscripts

Williams, M.<sup>G</sup>, and **P.P. Schmutz**. 2026. Space–Time Mapping and Identification of Sea Turtle Nesting Clusters on Pensacola Beach and Gulf Islands National Seashore, Florida. *Southeastern Geographer*, *66* (2), 152-180. [https://doi.org/10.1353/sgo.0.a981639](https://doi.org/10.1353/sgo.0.a981639)

**Schmutz, P.P.**, & T. Briggs<sup>U</sup>, and S.R. Seals. 2025. Lagging behind: Impact of non-native gravel within a coastal dune system. *Aeolian Research*, *72*, 100957. [https://doi.org/10.1016/j.aeolia.2024.100957](https://doi.org/10.1016/j.aeolia.2024.100957)

**Schmutz, P.P.** and A.P. Potter. 2024. Graffiti as Community Expression at Pensacola, Florida's Graffiti Bridge. *Southeastern Geographer*, *64* (4), 379-383. [https://doi.org/10.1353/sgo.2024.a942020](https://doi.org/10.1353/sgo.2024.a942020)

Corkran, R.<sup>U</sup>, A.E. Potter, and **P.P. Schmutz**. 2023. The Impacts of Climate Change on Coastal Georgia Heritage Tourism Sites. *Southeastern Geographer*, *63* (1), 36-53. [https://doi.org/10.1353/sgo.2023.0004](https://doi.org/10.1353/sgo.2023.0004)

Nelson, S.A.<sup>U</sup>, and **P.P. Schmutz**. 2021. The Utility of Using a Near-Infrared (NIR) Camera to Measure Beach Surface Moisture. *Geomorphology*, *391*, 107895. [https://doi.org/10.1016/j.geomorph.2021.107895](https://doi.org/10.1016/j.geomorph.2021.107895)

Harris, E.<sup>G</sup>, **P.P. Schmutz**, C. Jackson<sup>G</sup>, M. Anaya<sup>U</sup>, M. Johnson<sup>U</sup>, and G. Chapman<sup>U</sup>. 2020. Beach User Perception on the Economic and Ecological Importance of Sand Dunes at Pensacola Beach, Florida. *Southeastern Geographer*, *60* (4), 303-331. [https://doi.org/10.1353/sgo.2020.0026](https://doi.org/10.1353/sgo.2020.0026)

Gunn, A., **P.P. Schmutz**, M. Wanker, D.A. Edmonds, R.C. Ewing, and D.J. Jerolmack. 2020. Macroscopic flow disequilibrium over aeolian dune fields. *Geophysical Research Letters*, *47*, e2020GL088773. [https://doi.org/10.1029/2020GL088773](https://doi.org/10.1029/2020GL088773)

Jackson, C.<sup>G</sup>, **P.P. Schmutz**, M. Harwell, and C. Littles. 2020. The ecosystem service of property protection and exposure to environmental stressors in the Gulf of Mexico. *Ocean and Coastal Management*, *104*, 105017. [https://doi.org/10.1016/j.ocecoaman.2019.105017](https://doi.org/10.1016/j.ocecoaman.2019.105017)

**Schmutz, P.P.**, T. Briggs<sup>U</sup>, and P. Tereszkiewicz. 2019. The utility of an omni-directional photoelectronic sensor device to measure meso-scale variability in aeolian sediment transport activity. *Aeolian Research*, *36*, 61-67. [https://doi.org/10.1016/j.aeolia.2018.11.003](https://doi.org/10.1016/j.aeolia.2018.11.003)


### Technical Reports (Non-Peer-Reviewed)

**Schmutz, P.P**. 2021. Environmental assessment of the Captain Sams Spit and applicability of the property to accommodate a South Carolina State Park. *Report # 1.* South Carolina Department of Parks, Recreation, & Tourism.


### In Review

Cox, D.<sup>G</sup>, **P.P. Schmutz**, and S.R. Seals. In Review (2026). Modeling Sea Turtle Nesting Probability: Evaluating Loggerhead Nest Site Selection Using Presence–Pseudo-Absence Data. *Ecosphere*. 

Agin, J. <sup>U</sup>, **P.P. Schmutz**, P. Tereszkiewicz, and S.R. Seals. In Review (2026). Evaluating the Influence of Beach Wrack on Near-Surface Aerodynamics and Sediment Transport Processes. *Aeolian Research*.
